### ISSUE TITLE
Error LuaRocks build Windows

### ISSUE THREAD

**Issue by ghost** [nvs/lua-stormlib#7] opened 2020-12-21 02:39 UTC
I have this error : 
```
SBaseFileTable.obj : error LNK2019: unresolved external symbol GetBits referenced in GetFileEntryExact function
  Advice on the symbols defined and likely to correspond :
    "public: void __cdecl TMPQBits::GetBits(unsigned int,unsigned int,void *,int)" (?GetBits@TMPQBits@@QEAAXIIPEAXH@Z)
storm.lib(FileStream.obj) : error LNK2019: unresolved external symbol __imp_wsprintfA referenced in function "bool __cdecl BaseHttp_Read(struct TFileStream *,unsigned __int64 *,void *,unsigned long)" (?BaseHttp_Read@@YA_NPEAUTFileStream@@@PEA_KPEAXK@Z)

stormlib.dll: fatal error LNK1120: 2 external unsolved
```
When i try this command on Windows -> `luarocks install lua-stormlib STORM_LIBDIR="C:\Program Files (x86)\Lua\5.2\lib"`

The contents of the folder "C:\Program Files (x86)\Lua\5.2\lib" ->
- storm.lib
- StormLibRAD.lib

**Comment by nvs** [comment] 2020-12-21 04:53
Hey, thanks for the report. The version of lua-stormlib you were trying to build (i.e. 0.2.2) was intended for an older version of Stormlib (i.e. 9.22). I have tagged 0.2.3, which targets StormLib 9.23, and uploaded the rock to LuaRocks. Let me know if that resolves your issue.

**Comment by ghost** [comment] 2020-12-22 14:30
New Error :-/

```
Creation of the library stormlib.lib and the object stormlib.exp

storm.lib(FileStream.obj) : error LNK2019: unresolved external symbol __imp_wsprintfA referenced in function "bool __cdecl BaseHttp_Read(struct TFileStream *,unsigned __int64 *,void *,unsigned long)" (?BaseHttp_Read@@YA_NPEAUTFileStream@@@PEA_KPEAXK@Z)
stormlib.dll: fatal error LNK1120: 1 external unsolved

Error: Build error: Failed compiling module stormlib.dll
```

Same Error when i clone the repository and send command : `luarocks build STORM_LIBDIR="C:\Program Files (x86)\Lua\5.2\lib"`

**Comment by nvs** [comment] 2020-12-22 21:12
I don't think I can help you with this issue, as I only have experience with StormLib under Linux. I haven't dealt with development issues on Windows in maybe 15+ years. The first error involving the `GetBits` symbol was something I had seen as a difference between StormLib 9.22 and 9.23.

But this does seem like a Windows-centric problem, as the line of code specified within StormLib (in the `BaseHttp_Read` function, found within `src/FileStream.cpp`) is only included when building StormLib under Windows. I'm not sure how you got your version of StormLib, but perhaps you could try another one? Maybe a 32/64-bit issue?

Edit: I'm not versed enough with Windows development to know the best option, but including the following in that file fixes things:
```c
#pragma comment(lib, "user32.lib")
```

Now, there may also be an issue as far as name clashes on Windows in regards to the built DLL file (when using MSVC; I did not try MinGW). But this is a different topic (see #8).

**Comment by nvs** [comment] 2020-12-24 01:57
I added some changes to the rockspec in the `luarocks` branch. This should add better Windows support. I'll probably merge it after finding time to do more testing.

**Comment by nvs** [comment] 2022-05-28 23:12
With the release of 0.3 (mentioned in #9) I'm going to close this. I apologize, but I have neither the knowledge or desire to approach this issue on Windows. As mentioned in the README, I am open to pull requests.

**Closed as not planned by nvs** 2022-05-28 23:12 UTC
Labels: bug, task
